### ISSUE TITLE
ArgumentError: Package ZygoteRules does not have ChainRulesCore in its dependencies

### ISSUE THREAD

**Issue by Abinashbunty** [FZJ-PGI-12/QAOA.jl#27]
While executing `sherrington_kirkpatrick.ipynb` from [notebooks folder](https://github.com/FZJ-PGI-12/QAOA.jl/tree/master/notebooks), I get this error. Does the manifest file require some changes or is there some guide to resolve this issue?

Screeshot attached with more log information:

![image](https://user-images.githubusercontent.com/25522048/235527630-197605a5-4961-45bf-937b-d2fbe7b9e704.png)

Review tracking issue: openjournals/joss-reviews#5364

**Comment by timbode** [comment]
Noted. I'll look into it when I can. Not sure though if it's an issue with my pkg?

**Comment by Abinashbunty** [comment]
Maybe. I checked that based on [this](https://juliadiff.org/ChainRulesCore.jl/v1.0/converting_zygoterules.html), it might be useful to upgrade some existing _ZygotRules_ based functions to _ChainRules_.

**Comment by timbode** [comment]
> Maybe. I checked that based on [this](https://juliadiff.org/ChainRulesCore.jl/v1.0/converting_zygoterules.html), it might be useful to upgrade some existing _ZygotRules_ based functions to _ChainRules_.

The thing is, I am actually using `ChainRulesCore` and not `ZygoteRules`. So I'm not sure where this error comes from. Has this occured in other notebooks, too? What Julia version are you running?

**Comment by Abinashbunty** [comment]
@timbode It occurs on all the notebooks. I'm using Julia 1.8.5 from VS Code extension. 
![image](https://github.com/FZJ-PGI-12/QAOA.jl/assets/25522048/2317faf4-854f-4b83-963d-c5be294af68a)
