### ISSUE TITLE
Add community guidelines to documentation

### ISSUE THREAD

**Issue by babreu-ncsa** [FZJ-PGI-12/QAOA.jl#28]
*Guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support* is required in https://github.com/openjournals/joss-reviews/issues/5364

**Comment by timbode** [comment]
I've implemented the changes here: https://github.com/FZJ-PGI-12/QAOA.jl/commit/7a05f4144078221f9e6b0a23494b0cd893fdceab

**Comment by babreu-ncsa** [comment]
Thank you @timbode!
